# -*- coding: utf-8 -*-
"""Portfolio Python Juliette ODEYER.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTki-aiLTq57LXWC1j84zsvkQLOyMdPo

## **Financial analysis with Yahoo Finance**
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
# %matplotlib inline

!pip install yfinance

import yfinance as yf

msft = yf.Ticker("MSFT")

hist = msft.history(period="max")

hist

msft.actions # dividens, splits

msft.dividends

msft.splits

msft.financials

msft.major_holders

msft.institutional_holders

msft = yf.Ticker("MSFT")

msft.get_isin

msft.isin

msft.get_calendar

msft.options

hist.plot(kind="line", figsize=(12, 12), subplots=True)

#Major Indicies
major_indices = pd.read_html("https://finance.yahoo.com/world-indices")[0]

major_indices.head()

ticker_list = major_indices['Symbol'].str.replace("^","").str.lower().to_list()

len(ticker_list)

df = yf.download(ticker_list, period="1d", start="2020-01-13", end="2021-03-10")

df

df.columns

df.head()

adj_close = df.dropna(thresh=10, axis=1)['Adj Close']

adj_close.head()

adj_close.describe().T

adj_close.plot(figsize=(12,12), subplots=True);

adj_close = adj_close.drop("XAX", axis=1)

adj_close.plot(figsize=(12,20), subplots=True)

dji = adj_close['DJI']

dji

dji.resample("4M").mean()

dji.shift(1)

dji_per_change = dji / (dji.shift(1) - 1)

dji_per_change.plot(figsize=(12,6))

dji_log_returns_shift = np.log(dji / dji.shift(1))

dji_log_returns_shift.plot(figsize=(12,6));

dji.hist(bins=50, figsize=(12,12));

dji_log_returns_shift.hist(bins=50, figsize=(12,12));

dji_per_change.hist(bins=50, figsize=(12,12));